### ISSUE TITLE
Build failed on windows 

### ISSUE THREAD

**Issue by monkey-studio** [RadhiFadlillah/qamel#33]
When use qamel build on my windows 10 os, it failed with this info:
---
`Starting build process.

Load config file...done
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x63b110]

goroutine 1 [running]:
github.com/go-qamel/qamel/internal/cmd.dirExists(0xc00005e1e0, 0x5a, 0x5)
        G:/working/golang_work/src/github.com/go-qamel/qamel/internal/cmd/utils.go:31 +0xa0
github.com/go-qamel/qamel/internal/cmd.buildHandler(0xc0000b6840, 0x8e80c8, 0x0, 0x0)
        G:/working/golang_work/src/github.com/go-qamel/qamel/internal/cmd/build.go:108 +0x63d
github.com/spf13/cobra.(*Command).execute(0xc0000b6840, 0x8e80c8, 0x0, 0x0, 0xc0000b6840, 0x8e80c8)
        G:/working/golang_work/src/github.com/spf13/cobra/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000b6580, 0xc000043f50, 0xc0000a3f50, 0x405986)
        G:/working/golang_work/src/github.com/spf13/cobra/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        G:/working/golang_work/src/github.com/spf13/cobra/command.go:887
main.main()
        G:/working/golang_work/src/github.com/go-qamel/qamel/cmd/qamel/main.go:14 +0x63

`
---

How to solve this issue?pls.

this is profile info:
---------------

qamel profile print
Details of profile default
OS      : windows
Arch    : amd64
Static  : false
Qmake   : G:\Qt\Qt5_14_2\5.14.2\mingw73_64\bin\qmake.exe
Moc     : G:\Qt\Qt5_14_2\5.14.2\mingw73_64\bin\moc.exe
Rcc     : G:\Qt\Qt5_14_2\5.14.2\mingw73_64\bin\rcc.exe
Gcc     : G:\Qt\Qt5_14_2\Tools\mingw730_64\bin\gcc.exe
G++     : G:\Qt\Qt5_14_2\Tools\mingw730_64\bin\g++.exe
Objdump : G:\Qt\Qt5_14_2\Tools\mingw730_64\bin\objdump.exe
Windres : G:\Qt\Qt5_14_2\Tools\mingw730_64\bin\windres.exe

**Comment by monkey-studio** [comment]
Fixed:
I have more then one $GOPATH directory on my windows os, it will worked after remove the others only one path exist.

but now the problem is:
The App build success, but it can't run with error: 0xc000007b.

**Comment by monkey-studio** [comment]
Ok, it works now, because I have 32bit and 64bit version of Qt on my OS. It works only when use the right version of build profile setup and Qt version(32bit or 64bit).
